# Generated by Django 2.2.3 on 2020-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
