# Generated by Django 2.2.3 on 2020-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_program_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, null=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='value',
        ),
    ]
