# Generated by Django 2.2.3 on 2020-01-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200131_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grades', to='analysis.GradeValue'),
        ),
    ]
