# Generated by Django 2.2.3 on 2020-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20200131_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('school_code', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
